export default {
    GET_DATA: 'GET_DATA',

    INIT_CONNECTION: 'INIT_CONNECTION',
    SET_STATUS: 'SET_STATUS',
    SET_STATUS_STORE: 'SET_STATUS_STORE',

    ADD_NEW_USER: 'ADD_NEW_USER',
    SET_NEW_USER_STORE: 'SET_NEW_USER_STORE',

    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
    ADD_NEW_MESSAGE_STORE: 'ADD_NEW_MESSAGE_STORE',

    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    TOGGLE_CHAT_MODULE: 'TOGGLE_CHAT_MODULE',
    CHANGE_STATE_SELECTED_USER: 'CHANGE_STATE_SELECTED_USER',
}
